#!/usr/local/bin/fish
# vim: set ft=fish :

set keep_ts 0
set i 1
for arg in $argv
	if string match -iq -- $arg --keep-ts
		set keep_ts 1
		set -e argv[$i]
	end

	set i (math $i + 1)
end

set -l out $argv[-1]
set -l files $argv[1..-2]
set -l CONCAT (mktemp)

set ext (string replace -r -- '.*\.' '' $out)
set extra_cmd
if test $ext = "m4v"
	# work around http://trac.ffmpeg.org/ticket/7685
	set extra_cmd $extra_cmd -f mp4
end

# Must convert non-avi to AVI to avoid timestamp issues
set -g tmpdir (mktemp -d)
if test $keep_ts -eq 0 && not string match -q $ext avi
	set i 1
	for f in $files
		set outname (string replace -r '\.'$ext'$' .avi $f)
		command ffmpeg  -hide_banner -i $f -c copy $tmpdir/(basename $outname)
		touch -r $f $tmpdir/(basename $outname)
		set files[$i] $tmpdir/(basename $outname)
		set i (math $i + 1)
	end
end

for f in $files
	set -l absf (readlink -f -- $f)
	echo "file '$absf'"
end | tee $CONCAT

set ffmpeg_ok 0
# two inputs, first provides all videos, second is source of metadata
set cmd ffmpeg -hide_banner -fflags +genpts -f concat -safe 0 -i $CONCAT -i $files[1] -write_id3v2 1 -id3v2_version 3 -map_metadata:g 1:g -map_metadata:s:v 1:s:v -map 0:a? -map 0:v? -movflags +write_colr+use_metadata_tags+frag_keyframe+empty_moov+default_base_moof+faststart -frag_duration 1000000 -c copy $extra_cmd -export_xmp 1 -export_all 1 -vsync vfr $out
echo $cmd
command $cmd
and set ffmpeg_ok 1
rm $CONCAT

if test $ffmpeg_ok -eq 1
	# # Work around an ffmpeg bug where metadata is not copied to the correct section
	# # See https://trac.ffmpeg.org/ticket/4209
	# mp4extract moov/meta $files[1] moov-meta 2>| string replace "ERROR: " "";
	# test -f moov-meta && mp4edit --insert moov:moov-meta $out /dev/stdout | rewrite $out
	# rm -f moov-meta

	touch -r $files[1] $out
end

rm -rf $tmpdir
